version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000
    # restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9600"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3